<?php

namespace myunet\generate\controller;

use myunet\generate\model\GenerateTable;

class GenerateController extends BaseController{
    
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new GenerateTable();
    }

    /**
     * 代码生成表信息
     * @return \think\response\Json|\think\response\View
     */
    public function index(){
        if ($this->request->isPost()){
            $post = $this->request->post();
            $list = $this->model->list($post);
            return json(get_layui_page($list));
        }
        return view('generate/index');
    }

    public function addTable(){
        if ($this->request->isPost()){
            $post = $this->request->post();
            $list = $this->model->queryResult($post);
            return json(get_layui_page($list,$post));
        }
        return view('generate/add_table');
    }
}